In [59]:
import random
import numpy as np
from cnn.conv_layers import conv_layer_forward

batch_size = 1
num_filters = 2

channels_x, height_x, width_x = 3, 4, 4
height_w, width_w = 3, 3

stride = 1
pad_size = 1

x_shape = (batch_size, channels_x, height_x, width_x)
w_shape = (num_filters, channels_x, height_w, width_w)

input_layer = np.linspace(-0.4, 0.3, num=np.prod(x_shape)).reshape(x_shape)
weight = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)
bias = np.linspace(-0.1, 0.2, num=num_filters)

output_layer = conv_layer_forward(input_layer, weight, bias, pad_size, stride)

In [50]:
batch_size = 1
num_filters = 2

channels_x, height_x, width_x = 3, 5, 5
height_w, width_w = 3, 3

stride = 2
pad_size = 1

x_shape = (batch_size, channels_x, height_x, width_x)
w_shape = (num_filters, channels_x, height_w, width_w)

input_layer = np.linspace(-0.4, 0.3, num=np.prod(x_shape)).reshape(x_shape)
weight = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)
bias = np.linspace(-0.1, 0.2, num=num_filters)

stride = 2
pad_size = 1
# with zero-padding for x
height_y = int((height_x + 2*pad_size - height_w)/stride +1)
width_y = int((width_x + 2*pad_size - width_w)/stride +1)
output_layer = np.zeros((batch_size, num_filters, height_y, width_y))
print("y height,", height_y)
print("y width,", width_y)
output_layer.shape

y height, 3
y width, 3


(1, 2, 3, 3)

In [56]:
from scipy import signal
K = pad_size
Std = stride
for i in range(batch_size):
    for j in range(num_filters):
        out = np.zeros_like(output_layer[i,j,:,:])
        for cc in range(channels_x):
            x = input_layer[i,cc,:,:]
            filter_j = weight[j,cc,:,:]
            """    
            out_cc= signal.convolve2d(x, filter_j, mode="same",boundary='fill', fillvalue=0)
            out += out_cc
            """
            out_cc = np.zeros_like(out)
            x_pad = np.pad(x,(K,K),'constant', constant_values=(0, 0))
            for p in range(height_x, Std):
                for q in range(width_x, Std):
                    ypq = 0
                    for r in range(-1*K,(K+1)):
                        for s in range(-1*K,(K+1)):
                            ypq += x_pad[p+K+r,q+K+s]*filter_j[r+K,s+K]
                    out_cc[p,q]=ypq
            out+=out_cc
            
            output_layer[i,j,:,:] = bias[j]+out

    

In [57]:
output_layer

array([[[[-0.1, -0.1, -0.1],
         [-0.1, -0.1, -0.1],
         [-0.1, -0.1, -0.1]],

        [[ 0.2,  0.2,  0.2],
         [ 0.2,  0.2,  0.2],
         [ 0.2,  0.2,  0.2]]]])

In [55]:
correct_out = np.array(
    [[[[ 0.15470494,  0.28520674,  0.26826174,  0.14451626],   # y[0, 0, 0, :]
       [ 0.28745885,  0.47927338,  0.44816540,  0.25953031],   # y[0, 0, 1, :]
       [ 0.20956242,  0.35484143,  0.32373344,  0.17151746],   # y[0, 0, 2, :]
       [ 0.07288238,  0.14856283,  0.12403051,  0.03908872]],  # y[0, 0, 3, :]

      [[ 0.07425532,  0.04867523,  0.10001606,  0.15511441],   # y[0, 1, 0, :]
       [ 0.15335608,  0.17933360,  0.25065436,  0.26199920],   # y[0, 1, 1, :]
       [ 0.34860297,  0.46461662,  0.53593737,  0.44712967],   # y[0, 1, 2, :]
       [ 0.35662385,  0.45831794,  0.50207146,  0.41387796]]]] # y[0, 1, 3, :]
)


In [14]:
out = np.zeros((3,3)) + 1.2

In [18]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.pad(a,(1,1),'constant', constant_values=(0, 0))

array([[2., 2., 2., 2., 3.],
       [2., 1., 1., 1., 3.],
       [2., 1., 1., 1., 3.],
       [2., 1., 1., 1., 3.],
       [2., 3., 3., 3., 3.]])