In [21]:
import random
import numpy as np
import matplotlib.pyplot as plt
conf = {'layer_dimensions': [784, 128, 32, 10]}
params = None
dims = conf.get('layer_dimensions')
N = dims[0]
j = dims[1]
k = dims[2]
sigma = 2/N
weights = np.random.normal(0, sigma, (j, k))
bias = np.zeros((k))
params = {'weights': weights, 'bias': bias}

In [22]:
x = np.random.random((3, 2)) - 0.5

In [23]:
np.maximum(0,x)

array([[0.33058921, 0.        ],
       [0.04877941, 0.        ],
       [0.        , 0.        ]])

In [24]:
# Import the function you have implemented
from dnn.model import softmax
from dnn.tests import task_2b

# First, we load the dummy input and the expected output
input_Z, expected_S = task_2b()

# You should implement this function. Note that we often also use Ŷ to symbolise the output of the network.
S = softmax(input_Z)

# Check the result
#compare_result(expected_S, S, "softmax")

In [25]:
input_Z

array([[-3.  ,  0.  ,  3.  ],
       [-3.  ,  1.  ,  5.  ],
       [-4.5 ,  0.12, -0.12]])

In [33]:
expected_S.sum(axis=0)

array([1.        , 0.99999999, 0.99999999])

In [19]:
e_x = np.exp(input_Z-np.max(input_Z))
e_x.sum()

1.1747076831327086

In [27]:
e_x

array([[3.35462628e-04, 6.73794700e-03, 1.35335283e-01],
       [3.35462628e-04, 1.83156389e-02, 1.00000000e+00],
       [7.48518299e-05, 7.59701403e-03, 5.97602290e-03]])

In [35]:
e_x/e_x.sum(axis=0)

array([[0.44981622, 0.20636518, 0.11857876],
       [0.44981622, 0.56095872, 0.87618513],
       [0.10036756, 0.23267609, 0.0052361 ]])